# Generated by Django 4.2.8 on 2024-01-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emp_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='designation',
            field=models.CharField(choices=[('Inventory Manager', 'im'), ('Floor Supervisor', 'fs'), ('Staff', 'st')], default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'm'), ('Female', 'f'), ('others', 'o')], default=[('Others', 'o')], max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.PositiveIntegerField(default='00', max_length=10),
        ),
        migrations.DeleteModel(
            name='emp_db',
        ),
    ]
