# Generated by Django 4.2.8 on 2024-01-31 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_account_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='designation',
            field=models.CharField(choices=[('im', 'Inventory Manager'), ('fs', 'Floor Supervisor'), ('st', 'Staff')], default=[('st', 'Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 8, 53, 56, 257408)),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'others')], default=[('o', 'others')], max_length=10),
        ),
    ]
