# Generated by Django 4.2.8 on 2024-02-01 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_account_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 2, 1, 11, 36, 7, 639908)),
        ),
    ]
