# Generated by Django 4.2.8 on 2026-01-15 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_account_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.datetime(2026, 1, 15, 23, 17, 24, 602292)),
        ),
    ]
