# Generated by Django 4.2.8 on 2024-01-25 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.date(2024, 1, 25)),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 1, 25)),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'admin'), ('Manager', 'manager'), ('Supervisor', 'supervisor'), ('Employee', 'employee')], max_length=15),
        ),
    ]
