# Generated by Django 4.2.8 on 2024-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_gender_account_gender_account_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='Xxxx@0000', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='access',
            field=models.CharField(default=[('0', '0')], max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'admin'), ('Manager', 'manager'), ('Supervisor', 'supervisor'), ('Employee', 'employee')], default=[('Employee', 'employee')], max_length=15),
        ),
    ]
