# Generated by Django 4.2.8 on 2024-01-31 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_designation_alter_account_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='designation',
            field=models.CharField(choices=[('NA', 'NA'), ('im', 'Inventory Manager'), ('fs', 'Floor Supervisor'), ('st', 'Staff')], default=[('NA', 'NA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 10, 39, 33, 330462)),
        ),
    ]
