# Generated by Django 4.2.8 on 2024-02-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_no', models.CharField(max_length=10, unique=True)),
                ('Product_name', models.CharField(max_length=50, unique=True)),
                ('Product_type', models.CharField(default='Misc', max_length=80)),
                ('qty', models.PositiveIntegerField(default=0, max_length=100000)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
